package translate;

public class Constants {
	public final static String[][] mustTranslate={{"Skyline","天际"},{"kasara" ,"卡萨拉"},{"sky","天空"},{"Swiss","瑞士"},{"Asia","亚洲"},{"new","新"},
			{"InterContinental","洲际"},{"JW","万豪"},{"Aytthaya","大城府"},{"Sukhothai","素可泰"},{"Rattanakosin","拉达那哥欣"},{"Mandarin","文华"},
			{"AVANI","阿瓦尼"},{"Vista","Vista"},{"Anatara","安纳塔拉"},{"Shangri-La","香格里拉"},{"Isanook","爱思乐"},{"Sukosol","苏阁索"},
			{"Kkrungthep","曼谷"},{"Siam","暹罗"},{"Mae Nam","湄南"},{"Selandia","斯兰蒂亚"},{"Waverly","韦弗利"},{"Morroc","Morroc"},{"Splendid","华丽"},
			{"Scarlet","绯红"},{"Legacy","Legacy"},{"Caroline Astor","卡洛琳艾斯特"},{"John Jacobs Astoe","约翰雅各布艾斯特"},{"St.Regis","圣瑞吉"},{"Cool","酷"},
			{"kasara","卡萨拉"},{"Banyan","榕树"},{"Mu Dan","牡丹"},{"Ying Hua","樱花"},{"Jasmine","茉莉"},
			{"Crown","皇冠"},
			{"Elegance","优雅"},
			//{"Extreme","Extra","so","极致"},
			{"WOW","Fantastic","奇幻"},
			{"Radiance","璀璨"},
			{"G Club King Room","G 俱乐部房"},
			{"Okura","大仓"},
			{"Oasis","绿洲"},
			{"Author","作家"},
			{"Renaissance" ,"文艺复兴"},
			{"R Discoveries","R 发现房"},
			{"Spectacular","壮观"},
			{"Eternity","永恒"},
			{"Thai","泰式"},
			{"Exclusive","独家"},
			{"private","独立"},
			{"Comfy","舒适"},
			{"cozy","cosy","温馨"},
			{"Horizon","地平线"},
			{"space","太空"},
			{"zone","区"},
			{"Tower","塔"},
			{"Forest","森林"},
			{"Shared","共享"},
			{"Marvelous","非凡"},
			{"Multiple","多"},
			{"Circular","圆形"},
			{"full spectrum","全光谱"},
			{"Silhouette","剪影"},
			{"City","城市"},
			{"Grey mountain","灰山"},
			{"Bleached made","漂白"},
			{"Premier","顶级"},
			{"Grand","至尊"},
			{"super","超级"},
			{"Premium","尊享"},
			{"Luxury","奢华"},
			{"Deluxe","豪华"},
			{"Superior","高级"},
			{"Gold","黄金"},
			{"Junior","小型"},
			{"Executive","行政"},
			{"Standard","标准"},
			{"Classic","经典"},
			{"Theme","主题"},
			{"Presidential","总统"},
			{"Royal","皇家"},
			{"Prestige","威望"},
			{"Business","商务"},
			{"family","家庭"},
			{"Metropolitan","大都会"},
			{"club","俱乐部"},
			{"Corner","角落"},
			{"Signature","招牌"},
			{"budget","Economy","经济"},
			{"Advantage","优选"},
			{"Leisure","休闲"},
			{"Serenity","宁静"},
			{"Comfort","舒适"},
			{"Basic","基本"},
			{"Express","快捷"},
			{"Large","大型"},
			{"Small","小型"},
			{"Petite","娇小"},
			{"Duplex","复式"},
			{"Mini","迷你"},
			{"Spacious","宽敞"},
			{"Modern","Moderate","现代"},
			{"Youth","青春"},
			{"Wonderful","Wonder","奇幻"},
			{"Dream","梦幻"},
			{"Spa","Spa"},
			{"Lofty","阁楼"},
			{"Princess","公主"},
			{"connecting","Interconnecting","连通"},
			{"Bedroom","卧室"},
			{"One bedroom","1 bedroom","1 B/R","单卧室"},
			{"Two Bedrooms","2 bedrooms","2 B/R","两卧室"},
			{"Three bedroom","3 bedroom","3 B/R","三卧室"},
			{"Mixed","混合"},
			{"Female","ladies","女士"},
			{"Male","男士"},
			{"Disabled","残疾人"}
	};
	public final static String[][] tibu={
			{"Single","Sole use","单人"},
			{"Double","双人"},
			{"Twin","双床"},
			{"Semi double","Semi DBL","小型大床"},
			{"King","大床"},
			{"Queen","大床"},
			{"Triple","三人"},
			{"Quad","quadruple","四人"},
			{"Bunk Bed","双层床"},
			{"Panoramic View","全景"},
			{"Sea View","海景"},
			{"Ocaen View","海景"},
			{"City View","城景"},
			{"Garden View","园景"},
			{"River View","河景"},
			{"Harbour View","港景"},
			{"Pool View","池景"},
			{"Park view","公园景"},
			{"Terrace","阳台"},
			{"Balcony","阳台"},
			{"Kitchen","厨房"},
			{"sofa","沙发"},
			{"Garden","花园"}
	};
	public final static String[][] roomType={
			{"Dormitory","Dorm","宿舍"},
			{"Shared Dormitory","Shared Dorm","共用宿舍"},
			{"residence","公寓"},
			{"Apartment","公寓"},
			{"Suite","Suite room","套房"},
			{"Studio","一室公寓"},
			{"Studio Suite","一室公寓套房"},
			{"Penthouse","阁楼"},
			{"Guest Room","客房"},
			//{"room","房"},
			{"Spa Package","Spa 套房"},
			{"cabana","小屋"},
			{"Cottage","小屋"},
			{"villa","别墅"},
			{"Retreat","度假村"},
			{"Run of House","ROH","Run of the House","不指定房型"}
	};
	public final static String[][] attach={
			{"shared bathroom","-共用浴室"},
			{"private bathroom","-私人浴室"}
	};
	

}
